
env = Environment(tools = ["default", "concatjs", "uglifyjs", "filtered_glob"])

#
# Compress Javascript source files
#

env.ConcatJS("sozi")
js_files = env.UglifyJS("sozi.min.js", "sozi.cat.js")

js_files += env.UglifyJS("extras/sozi_extras_media.min.js", "extras/sozi_extras_media.js")

#
# Generate API documentation
# TODO use custom template and stylesheet
#

Command("api", env.FilteredGlob("*.js", ["sozi.min.js", "sozi.cat.js"]), "jsdoc --private --directory=$TARGET $SOURCES")

Return("js_files")

