
env = Environment(tools = ["default", CONCATENATE_JS, UGLIFY_JS])

env.ConcatenateJS("sozi.cat.js", "sozi.js")
js_files = env.UglifyJS("sozi.min.js", "sozi.cat.js")

js_files += env.UglifyJS("extras/sozi_extras_media.min.js", "extras/sozi_extras_media.js")

Return("js_files")

