
env = Environment(tools = ["default", "concatjs", "uglifyjs", "filtered_glob"])

Import("prefix common_install")

#
# Compress Javascript source files
#

env.ConcatJS("sozi")
js_files = env.UglifyJS("sozi.min.js", "sozi.cat.js")

js_files += env.UglifyJS("extras/sozi_extras_media.min.js", "extras/sozi_extras_media.js")

#
# Generate API documentation
# TODO use custom template and stylesheet
#

if env.WhereIs("jsdoc"):
    Command("api", env.FilteredGlob("*.js", ["sozi.min.js", "sozi.cat.js"]), "jsdoc --private --directory=$TARGET $SOURCES")
    Install(prefix + "/share/doc/sozi", "api")


Return("js_files")

