
AddOption("--player-prefix",
          dest="player-prefix",
          type="string",
          nargs=1,
          action="store",
          metavar="DIR",
          default="/usr",
          help="Prefix directory for standalone player installation")

player_prefix_dir = GetOption("player-prefix")
Alias("install-player", player_prefix_dir)

#
# Build player files
#

player_files = SConscript("js/SConscript")
player_files += SConscript("css/SConscript")

Install(player_prefix_dir + "/share/sozi", player_files)

#
# Generate header for C-based tools
# TODO rewrite gen_header as an SCons tool in Python
#

Import("sozi_version_file")
header_file = Command("sozi.h", player_files + sozi_version_file, "site_scons/site_tools/gen_header $TARGET $SOURCES")
Install(player_prefix_dir + "/include", header_file)

Return("player_files")

