
Import("prefix common_install")

#
# Build player files
#

player_files = SConscript("js/SConscript")
player_files += SConscript("css/SConscript")

player_install = Install(prefix + "/share/sozi", player_files)


#
# Generate header for C-based tools
# TODO rewrite gen_header as an SCons tool in Python
#

Import("sozi_version_file")
header_file = Command("sozi.h", player_files + sozi_version_file, "site_scons/site_tools/gen_header $TARGET $SOURCES")

player_install += Install(prefix + "/include", header_file)

Alias("install-player", [player_install, common_install])

Return("player_files")

