#!/bin/sh
# This tool generate a C header that declare one static string
# initialized with the content of input files.
# Usage :
#  ./gen_header output_file input_file_1 input_file_2 ... 
# Arguments
#  output_file is the resulting header file
#  input_file_* are the input files (js, css, etc)

if [ $# -lt 2 ]
then
  echo "Usage: $0 output_file input_file_1 [input_file_1 ...]"
  exit 65 # E_BADARGS=65
fi

header_file=$1
header_name=`basename $1 | sed -e 's/\./_/g'`
shift

echo "#ifndef __${header_name}__" >  ${header_file}
echo "#define __${header_name}__" >> ${header_file}
echo "" >> ${header_file}

while [ "$1" ]; do

  var_name=`basename $1 | sed -e 's/\./_/g'`

  echo "static const char ${var_name}[] =" >> ${header_file} 

  # escape double quotes
  # wrap long lines (msvc don't allow too long lines)
  # FIXME : can be improved (try sed -e 's/.\{76\}/&"\n"/g' ?)
  cat $1 | tr -d '\n' | fold | sed -e 's/"/\\"/g' -e 's/^/\"/g;s/$/\"/g' >> ${header_file}

  echo ";" >> ${header_file}
  echo "" >> ${header_file}

  shift

done

echo "#endif /* __${header_name}__ */" >> ${header_file}
