
from datetime import datetime

env = Environment()

sozi_version = datetime.utcnow().strftime("%y.%m-%d%H%M%S")

env.Command("sozi/version.py", "sozi/version.tpl.py", "sed s/@SOZI_VERSION@/{0}/ $SOURCE > $TARGET".format(sozi_version))

