
import os

env = Environment(tools = ["default", "gettext"])

#
# Insert Sozi version in sozi/version.py
#

Import("sozi_version")
env.Command("sozi/version.py", "sozi/version.tpl.py", "sed s/@SOZI_VERSION@/{0}/ $SOURCE > $TARGET".format(sozi_version))

#
# Compile translation files
#

src_files = Glob("*.py") + Glob("sozi/*.py") + ["sozi/ui.glade"]

env.POTUpdate("sozi", src_files)

po_files = Glob("sozi/lang/*.po")
mo_files = env.MOFiles(po_files)

for mo_file in mo_files:
    lang = os.path.splitext(mo_file.name)[0]
    InstallAs("sozi/lang/{0}/LC_MESSAGES/sozi.mo".format(lang), mo_file)
